const ERROR_INTERNAL = 'ERROR_INTERNAL';
const ERROR_NOT_AUTHENTICATED = 'ERROR_NOT_AUTHENTICATED';
const ERROR_USER_NOT_FOUND = 'ERROR_USER_NOT_FOUND';
const ERROR_RECEIVER_ALREADY_HAS_PARTNER = 'ERROR_RECEIVER_ALREADY_HAS_PARTNER';
const ERROR_RECEIVER_EMAIL_REQUIRED = 'ERROR_RECEIVER_EMAIL_REQUIRED';
const ERROR_RECEIVER_EMAIL_IS_SENDERS = 'ERROR_RECEIVER_EMAIL_IS_SENDERS';
const ERROR_USER_HAS_NO_PARTNER = 'ERROR_USER_HAS_NO_PARTNER';

module.exports = {
    ERROR_INTERNAL: ERROR_INTERNAL,
    ERROR_NOT_AUTHENTICATED: ERROR_NOT_AUTHENTICATED,
    ERROR_USER_NOT_FOUND: ERROR_USER_NOT_FOUND,
    ERROR_RECEIVER_ALREADY_HAS_PARTNER: ERROR_RECEIVER_ALREADY_HAS_PARTNER,
    ERROR_RECEIVER_EMAIL_REQUIRED: ERROR_RECEIVER_EMAIL_REQUIRED,
    ERROR_RECEIVER_EMAIL_IS_SENDERS: ERROR_RECEIVER_EMAIL_IS_SENDERS,
    ERROR_USER_HAS_NO_PARTNER: ERROR_USER_HAS_NO_PARTNER
};