const ERROR_INTERNAL = 'ERROR_INTERNAL';
const ERROR_NOT_AUTHENTICATED = 'ERROR_NOT_AUTHENTICATED';
const ERROR_USER_NOT_FOUND = 'ERROR_USER_NOT_FOUND';
const ERROR_RECEIVER_ALREADY_HAS_PARTNER = 'ERROR_RECEIVER_ALREADY_HAS_PARTNER';
const ERROR_RECEIVER_EMAIL_OR_UID_REQUIRED = 'ERROR_RECEIVER_EMAIL_OR_UID_REQUIRED';
const ERROR_CAN_NOT_ADD_SELF = "ERROR_CAN_NOT_ADD_SELF";
const ERROR_USER_HAS_NO_PARTNER = 'ERROR_USER_HAS_NO_PARTNER';

module.exports = {
    ERROR_INTERNAL: ERROR_INTERNAL,
    ERROR_NOT_AUTHENTICATED: ERROR_NOT_AUTHENTICATED,
    ERROR_USER_NOT_FOUND: ERROR_USER_NOT_FOUND,
    ERROR_RECEIVER_ALREADY_HAS_PARTNER: ERROR_RECEIVER_ALREADY_HAS_PARTNER,
    ERROR_RECEIVER_EMAIL_OR_UID_REQUIRED: ERROR_RECEIVER_EMAIL_OR_UID_REQUIRED,
    ERROR_CAN_NOT_ADD_SELF: ERROR_CAN_NOT_ADD_SELF,
    ERROR_USER_HAS_NO_PARTNER: ERROR_USER_HAS_NO_PARTNER
};